### ISSUE TITLE
List of all working ESP32/ESP8266 boards

### ISSUE THREAD

**Issue by darknessblade** [techdregs/Home-Assitant-Voice-Remote#1]
Is there a FULL list of all boards supported that are working/tested

Would a board like:
[aliexpress.com/item/4000140431251.html?](url)
Work with the firmware.

If this board is supported would it also be possible to have the display show the voice-input text as well?

**Comment by techdregs** [comment]
It's possible for this to work on most ESP32 boards, but specific configuration would vary depending on which board you use. You would only be able to use my code for the specific board I used, the Adafruit Feather v2. For other boards, this would be an example that you could modify to work with whatever board you are using.
